mattermost:
  url: https://mattermost.mit.edu
# First matching mapping is used
mappings:
- channel: administrivia
  class: sipb
  instance: administrivia
- channel: archiving
  class: sipb
  instance: archiving
#- channel: badges
#- channel: bhchp-ideas
- channel: book-recs
  class: sipb
  instance: book-recs
#- channel: cloud-credits
- channel: cluedumps
  class: sipb
  instance: cluedumps
#- channel: courseroad-dev
- channel: covid-19-task-force
  class: sipb
  instance: covid-19-task-force
- channel: cpw
  class: sipb
  instance: cpw
#- channel: discord
- channel: game-night
  class: sipb
  instance: game-night
- channel: get-help
  class: sipb
  instance: help
#- channel: hyades-development
- channel: iap-planning
  class: sipb
  instance: iap
#- channel: infracomm
- channel: machine-rooms
  class: sipb
  instance: smr
- channel: memes
  class: sipb
  instance: memes
#- channel: mentorship-program
- channel: modern-athena
  class: sipb
  instance: modern-athena
- channel: office
  class: sipb
  instance: office
- channel: office-heads
  class: sipb
  instance: office-heads
- channel: office-quotes
  class: sipb
  instance: oq
- channel: other
  class: sipb
  instance: other
- channel: other-other
  class: sipb
  instance: other-other
- channel: out-of-the-loop
  class: sipb
  instance: out-of-the-loop
#- channel: paper-plate-awards
#- channel: programming-jackbox
- channel: rush-announce
  class: sipb
  instance: rush
#- channel: sibp-supercloud
#- channel: sipb-library
#- channel: sipb-wisp
- channel: stapler
  class: sipb
  instance: stapler
- channel: technical
  class: sipb
  instance: technical
- channel: town-square
  class: sipb
  instance: town-square
#- channel: uplink
- channel: when-office-open
  class: sipb
  instance: door
- channel: when-office-open
  class: sipb-auto
  instance: door
# Classes without instances are listed last, so individual instances can be peeled off first.
- channel: scripts
  class: scripts
- channel: test
  class: mattermost-test
- channel: xvm
  class: xvm
- channel: sipb
  class: sipb
- channel: unsipb
  class: unsipb
